image: iiasa/gams:24.8.5  # python:3.8-slim  python:3.7-alpine

pages:
  stage: deploy
  script:
  - cd /opt/gams/gams24.8_linux_x64_64_sfx/
  - ls -la
  - apt-get install python3.6
  - apt-get install python3-pip
  # - python setup.py install
  # - pip install -U sphinx
  # - pip install -U sphinx-rtd-theme
  # - sphinx-build -b html ./docsfiles public
  artifacts:
    paths:
    - public
  only:
  - master
