image: iiasa/gams:24.8.5  # python:3.8-slim  python:3.7-alpine

pages:
  stage: deploy
  script:
  - add-apt-repository ppa:deadsnakes/ppa
  - apt-get update
  - apt-get install -y python3.6
  - apt-get install -y python3-pip
  - apt-get install -y tree
  - cd /opt/gams/gams24.8_linux_x64_64_sfx/apifiles/Python/api_36/
  - python3 setup.py install
  - cd /
  - tree -a
 # - python3 setup.py install
 # - pip3 install -U sphinx
 # - pip3 install -U sphinx-rtd-theme
 # - sphinx-build -b html ./docsfiles public
  artifacts:
    paths:
    - public
  only:
  - master
