image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - python setup.py install -y
  - pip install -U sphinx
  - pip install -U sphinx-rtd-theme
  - sphinx-build -b html ./docsfiles public
  artifacts:
    paths:
    - public
  only:
  - master
