image: iiasa/gams:24.8.5

pages:
  stage: deploy
  script:
  - add-apt-repository ppa:deadsnakes/ppa
  - apt-get update
  - apt-get install -y python3.6
  - apt-get install -y python3-pip
  - apt-get install -y python3-matplotlib
  - apt-get install -y python3-dateutil
  - python3.6 -m pip install pip
  - python3.6 -m pip install --upgrade pip
  - python3.6 -m pip install pipenv
  - cd /opt/gams/gams24.8_linux_x64_64_sfx/apifiles/Python/api_36/
  - python3.6 setup.py install
  - cd /builds/diw-evu/dieter_public/dieterpy/
  - python3.6 setup.py install
  - python3.6 -m pip install -U sphinx
  - python3.6 -m pip install -U sphinx-rtd-theme
  - sphinx-build -b html ./docs public
  artifacts:
    paths:
    - public
  only:
  - master
